format = "$username$hostname$battery$all"
add_newline = false

[[battery.display]]
threshold = 100
style = "bold bright-green"

[directory]
truncate_to_repo = false
truncation_length = 10

[package]
disabled = true

[status]
disabled = false

[username]
show_always = true
format = "[$user]($style) ğŸ™ "
